### ISSUE TITLE
safari on windows (version 5) seems to not take the help

### ISSUE THREAD

**Issue by OliverLeitner** [jimmywarting/FormData#51]
hi,

thanks alot for the really helpful extension, it fixed my issues so far with ie...

in safari it doesnt seem to work though...

`TypeError: 'undefined' is not a function (evaluating 'formData.set('jsondata', jqXHR.responseText)')`

other things like forEach dont seem to work either...

have you had that experience, and if so, maybe you have a trick on howto load your plugin to work with all browsers...

**Comment by jimmywarting** [comment]
Safari stop maintaining the windows version several years ago.
latest version released was v5 on 2010-05-09 (18 years ago)

**Comment by anddoutoi** [comment]
It doesn't work in IE 5 for Mac or Netscape 4.78 for Win95 either.

**Comment by anddoutoi** [comment]
Just trolling ;)

**Comment by jimmywarting** [comment]
I figured

**Comment by OliverLeitner** [comment]
ahh, thanks alot... i think ill wait for some mac user to mail me about stuff if its not working...

sad state of affairs with apple...

**Comment by jimmywarting** [comment]
Correction: windows user.

mac users will have an up to date browser
